#!/bin/bash

echo " "

# Check to see if updater is already installed
if [ -f "/usr/local/bin/dnsupdater.py" ] | [ -f "/etc/systemd/system/dnsupdater.service" ]
then
  echo "Already installed?"
  echo "Use url2box/godaddy/purge first if you wish to remove the existing updater."
  echo " "
  exit 1	
fi

# Check to see if nginx is there
if [ ! -d "/etc/nginx" ]
then
  echo "You need to install the gateway first:  gateway/install "
  echo " "
  exit 1
fi

# At least check that there are 3 args
if [ "$#" -gt 2 ]
then
  echo " "
  echo "Installing DNS updater to link your GoDaddy domain $1 with this webdevbox."

  echo " "
  echo "Writing the DNS updater to /usr/local/bin..."
  sudo cp url2box/godaddy/dnsupdater.py /usr/local/bin/dnsupdater.py
  sudo sed -i "s/GODADDYPUBLICKEY/$1/g" /usr/local/bin/dnsupdater.py
  sudo sed -i "s/GODADDYPRIVATEKEY/$2/g" /usr/local/bin/dnsupdater.py
  shift 2
  sudo sed -i "s/GODADDYDOMAIN/$*/g" /usr/local/bin/dnsupdater.py

  echo " "
  echo "Writing your initial HTML index page to /var/www/html/webdevbox.html..."
  sudo cp url2box/webdevbox.html /var/www/html/webdevbox.html
  sudo sed -i "s/PUBLICURL/$1/g" /var/www/html/webdevbox.html
  sudo sed -i "s/URLSERVICE/godaddy/g" /var/www/html/webdevbox.html

  echo " "
  echo "Setting up DNS updater log file..."
  rm -f dnsupdater.log
  echo "Installed GoDaddy dnsupdater." >> dnsupdater.log
  sudo rm -f /usr/local/bin/dnsupdater.log
  sudo mv dnsupdater.log /usr/local/bin/dnsupdater.log
  sudo chmod a+rw /usr/local/bin/dnsupdater.log

  echo " "
  echo "Installing, enabling, and staring the DNS Updater..."
  sudo cp url2box/godaddy/dnsupdater.service /etc/systemd/system/dnsupdater.service
  sudo chmod 777 /etc/systemd/system/dnsupdater.service
  sudo systemctl daemon-reload
  sudo systemctl enable dnsupdater
  sudo systemctl start dnsupdater

  echo " "
  echo "---------------------------"
  echo " "
  echo "Your GoDaddy DNS Updater is up and running.  Next steps: "
  echo " -  Check the log with the command 'cat /usr/local/bin/dnsupdater.log'"
  echo " -  Go to http://$1 in your browser to access your webdevbox via your GoDaddy domain."
  echo " "
  echo "If these are both good, you're ready to certify:  certify/install $1 "
  echo " "
else
  echo " "
  echo "Ahem!  That's just wrong.  I was expecting something like this:"
  echo " "
  echo "    url2box/godaddy/install \"xyz.com\" \"ThIs1sAveryLONGpublicKEY\" \"AshorterPRIVATEkey\" "
  echo " "
  echo "where xyz.com is the GoDaddy domain you are using as the public face of your"
  echo "webdevbox, and the two keys come from going to developer.godaddy.com and clicking"
  echo "the Keys link and creating Production keys."
  echo " "
fi  

