#!/bin/bash

sudo apt-get update
sudo apt-get purge nginx*
sudo apt-get autoremove nginx
sudo apt-get --purge remove nginx
sudo apt-get autoremove
sudo apt-get autoclean

sudo apt-get update
sudo apt-get -f install nginx
exit


sudo ufw allow 'Nginx Full'
sudo openssl req -x509 -nodes -days 1000 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
sudo cp extras/nginxself.conf /etc/nginx/snippets/self-signed.conf
sudo cp extras/nginxsslparms.conf /etc/nginx/snippets/ssl-params.conf
sudo cp /etc/nginx/sites-available/default extras/nginxsitesback
sudp cp extras/nginxsites /etc/nginx/sites-available/default
