#!/bin/bash

############################################################
#
# Install Tomcat web server and make it autostart on reboot
#
# Example:  tomcat/install 8080 admin 5ecret
# Installs tomcat, listening on port 8080.  Tomcat Manager
# signon:  user admin, password 5ecret.
#
############################################################

echo " "
ok=1
if [ "$#" -eq 3 ]
then
  tomcatport=$1
  tomcatuser=$2
  tomcatpass=$3
  case $tomcatport in 
    *[!0-9]*)  ok=0 ;;
    *)         ok=1 ;;
  esac
  if [ "$ok" == "0" ]
  then
    echo "I did not install Tomcat because I was expecting a numeric"
    echo "port number to be specified.  Example:"
    echo " "
    echo "   tomcat/install 8080 admin sigh"
    echo " "
    echo "This sets up Tomcat on port number 8080, with the Tomcat"
    echo "Manager authorized for user admin, password sigh."
    echo " "
    exit 1
  fi
else
  echo "I was expecting 3 parameters:"
  echo " -  The port number for Tomcat"
  echo " -  The user name for the Tomcat's administrative user"
  echo " -  The password for the admin user"
  echo " "
  echo "Example:"
  echo " "
  echo "   tomcat/install 8080 admin sigh"
  echo " "
  echo "This sets up Tomcat on port number 8080, with the Tomcat"
  echo "Manager authorized for user admin, password sigh."
  echo " "
  exit 1
fi

# We appear to have a valid command, complete with port spec
if [ -d "/opt/tomcat" ]
then
  echo "It looks like Tomcat is already installed..?  I'll do nothing here."
  echo "But if you want to re-install, you can remove what's already there with"
  echo " "
  echo "    tomcat/purge"
  echo " "
  exit 1
fi

# Save the port spec for later
rm -f tomcat/setport
echo "#!/bin/bash" > tomcat/setport
echo "tomcatport=$tomcatport" >> tomcat/setport
chmod +x tomcat/setport

# Actually install Tomcat now

# Set up Tomcat as a systemd service
sudo cp tomcat/tomcat.service /etc/systemd/system/tomcat.service

# Establish a Tomcat group, containing user tomcat
sudo groupadd tomcat
sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat

# Go get Tomcat 8.0.47
cd /tmp
rm -f apache-tomcat-8*
curl -O http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v8.0.48/bin/apache-tomcat-8.0.48.tar.gz
sudo mkdir /opt/tomcat
sudo tar xzf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1

# Clean up configurations and permissions
cd ~
sudo sed -i "s/8080/$tomcatport/g" /opt/tomcat/conf/server.xml
sudo cp /opt/tomcat/conf/tomcat-users.xml temp.xml
sudo chmod a+wr temp.xml
sed -i "s@<\/tomcat-users>@  <role rolename=\"manager-gui\"\/>@g" temp.xml
echo "  <user username=\"$tomcatuser\" password=\"$tomcatpass\" roles=\"manager-gui\"/>" >> temp.xml
echo "</tomcat-users>" >> temp.xml
sudo cp temp.xml /opt/tomcat/conf/tomcat-users.xml
rm temp.xml
sudo chgrp -R tomcat /opt/tomcat
sudo chmod -R g+r /opt/tomcat/conf
sudo chmod g+x /opt/tomcat/conf
sudo chown -R tomcat /opt/tomcat/webapps/ /opt/tomcat/work/ /opt/tomcat/temp/ /opt/tomcat/logs/

# Set it up to auto-start at startup... and start it now
sudo systemctl daemon-reload
sudo systemctl enable tomcat
sudo systemctl start tomcat

# Declare victory
echo " "
echo "Tomcat is now up and running.  Try it out:  with your browser, go to"
echo " "
echo "    http://localhost:$tomcatport "
echo " "
echo "You should be greeted with the Tomcat Welcome page."
echo " "


