#!/bin/bash

############################
#
# Install no-ip.com dynamic DNS updater.
# Make it auto-start on reboot.
#
############################

if [ ! -f /usr/local/bin/noip2 ]
then
  echo " "
  echo "To get the no-IP updater to automatically run at startup, first"
  echo "we need the updater itself.  That is described in the no-IP site:"
  echo " "
  echo "www.noip.com/support/knowledgebase/installing-the-linux-dynamic-update-client-on-ubuntu/"
  echo " "
  echo "Or you could just type the following commands:"
  echo "  sudo -s"
  echo "  cd /usr/local/src"
  echo "  wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz"
  echo "  tar xf noip-duc-linux.tar.gz"
  echo "  cd noip-2.1.9-1/"
  echo "  make install"
  echo "and you will be then prompted for your No-IP credentials.  Then say"
  echo "  exit"
  echo "  dnsnoip/install"
  echo "and life should be good."
  exit
fi

sudo systemctl stop noip
sudo cp dnsnoip/noip.service /etc/systemd/system/noip.service
sudo chmod 700 /usr/local/bin/noip2
sudo chown root:root /usr/local/bin/noip2
sudo systemctl enable noip
sudo systemctl start noip

