#!/bin/bash

# Used to blow away GoDaddy DNS updater.

echo " "
echo "Blowing away No-IP Dynamic IP updater."
echo " "
sudo systemctl stop noip
sudo systemctl disable noip
sudo rm /etc/systemd/system/noip.service
sudo rm /usr/local/bin/noip*
sudo rm /usr/local/src/noip*

