#!/bin/bash
echo " "
echo "Adding certbot repository..."
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt-get update
sudo apt-get install -y python-certbot-nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/precertify
sudo sed -i "s/server_name _/server_name $1 www.$1/g" /etc/nginx/sites-available/default
sudo systemctl reload nginx
echo " "
echo "Generating certificates.  Right answer is 1."
sudo certbot --nginx -d $1 -d www.$1
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/postcertify
sudo cp dnsgodaddy/certified /etc/nginx/sites-available/default
sudo sed -i "s/GODADDYDOMAIN/$1/g" /etc/nginx/sites-available/default
sudo sed -i "s/server_name _/server_name $1 www.$1/g" /etc/nginx/sites-available/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/certified
sudo systemctl reload nginx
echo " "
echo "You are now set to use $1 to securely access your webdevbox from the public internet."
echo "All traffic encrypted.  $1/docs redirects to localhost:8080/docs;  anything else will"
echo "serve static content from /var/www/html.  To change this behaviour, edit nginx config"
echo "/etc/nginx/sites-available/default which has embedded hints for you..."

