#!/bin/bash

# At least check that there are 3 args
if [ "$#" -eq 3 ]
then
  echo " "
  echo "Installing DNS updater for a GoDaddy domain."
  echo " "
  echo "Getting some prerequisites..."
  sudo systemctl stop dnsupdater
  pip3 install godaddypy pif

  echo " "
  echo "Writing the DNS updater..."
  sudo cp dnsgodaddy/dnsupdater.py /usr/local/bin/dnsupdater.py
  sudo sed -i "s/GODADDYDOMAIN/$1/g" /usr/local/bin/dnsupdater.py
  sudo sed -i "s/GODADDYPUBLICKEY/$2/g" /usr/local/bin/dnsupdater.py
  sudo sed -i "s/GODADDYPRIVATEKEY/$3/g" /usr/local/bin/dnsupdater.py

  echo " "
  echo "Writing your initial HTML index page (webdevbox.html)..."
  sudo cp dnsgodaddy/webdevbox.html /var/www/html/webdevbox.html
  sudo sed -i "s/GODADDYDOMAIN/$1/g" /var/www/html/webdevbox.html

  echo " "
  echo "Setting up DNS updater log file..."
  echo "Installed GoDaddy dnsupdater." >> dnsupdater.log
  sudo mv dnsupdater.log /usr/local/bin/dnsupdater.log
  sudo chmod a+rw /usr/local/bin/dnsupdater.log

  echo " "
  echo "Installing, enabling, and staring the DNS Updater..."
  sudo cp dnsgodaddy/dnsupdater.service /etc/systemd/system/dnsupdater.service
  sudo chmod 644 /etc/systemd/system/dnsupdater.service
  sudo systemctl daemon-reload
  sudo systemctl enable dnsupdater.service
  sudo systemctl start dnsupdater.service

  echo " "
  echo "---------------------------"
  echo " "
  echo "Type 'cat /usr/local/bin/dnsupdater.log' to see what your DNS updater is doing."
  echo "Go to $1 in your browser to access your webdevbox via your GoDaddy domain."
  echo "Your next step:  dnsgodaddy/certify $1 "
  echo " "
else
  echo " "
  echo "Ahem!  That's just wrong.  I was expecting something like this:"
  echo " "
  echo "    dnsgodaddy/install \"xyz.com\" \"ThIs1sAveryLONGpublicKEY\" \"AshorterPRIVATEkey\" "
  echo " "
  echo "where xyz.com is the GoDaddy domain you are using as the public face of your"
  echo "webdevbox, and the two keys come from going to developer.godaddy.com and clicking"
  echo "the Keys link and creating Production keys."
  echo " "
fi  
