#!/bin/bash

# Used to blow away GoDaddy DNS updater.

echo " "
echo "Blowing away GoDaddy DNS updater."
echo " "
sudo systemctl stop dnsupdater
sudo systemctl disable dnsupdater
sudo rm /etc/systemd/system/dnsupdater.service
sudo rm /usr/local/bin/dnsupdater*

