#!/bin/bash

############################################################
#
# Remove mariadb/mysql server installed by 'install' script
#
############################################################

echo " "
if [ "$#" -eq 0 ]
then
  echo "Blowing away mysql."
  echo " "
  sudo systemctl stop mysql
  sudo killall -KILL mysql mysqld_safe mysqld
  
  sudo apt-get remove dbconfig-mysql dbconfig-common -y
  sudo rm -rf /etc/dbconfig-common
  
  sudo apt-get --purge remove mysql-server mysql-client mysql-common -y
  sudo apt-get autoremove -y
  sudo apt-get autoclean
  
  sudo deluser --remove-home mysql
  
  sudo rm -rf /var/lib/mysql
  sudo rm -rf /var/log/mysql
  sudo rm -rf /var/run/mysql
  sudo rm -rf /etc/mysql
  sudo rm -rf ~/.mysql
  
  echo " "
  echo "mysql has been purged."
  echo " "
else
  echo "mysql/purge takes no parameters.  Were you expecting something else?"
  echo " "
  exit 1
fi

