#!/bin/bash
echo " "

# Check to see if it's already installed
if [ -d /etc/letsencrypt ] | [ -f /etc/nginx/sites-available/precertify.conf ] | [ -f /etc/nginx/sites-available/certified.conf ]
then
  echo "There are already certbot certificate(s), so it would seem "
  echo "certbot is already installed.  If you want to remove what's "
  echo "there and clean re-install, use these commands:"
  echo " "
  echo "    certify/purge"
  echo "    certify/install"
  echo " "
  exit 1
fi


# check parameters ... there should be at least 1
if [ "$#" -eq 0 ]
then
  echo " "
  echo "Installing certbot for nginx..."
  sudo apt-get install -y python-certbot-nginx
  echo " "
  echo "Now you can create a certificate byproviding a list of URLs"
  echo "you want to include, like this:"
  echo "  "
  echo "    certify/urls xyz.com www.xyz.com xyz.ddns.net"
  echo "  "
  echo "Or, if you'd like to check your URLs before you go for a"
  echo "certificate, you could check verify they resolve to your"
  echo "host first:"
  echo " "
  echo "    certify/check xyz.com www.xyz.com xyz.ddns.net"
  echo " "
else
  echo " "
  echo "certify/install takes no parameters.  Just say"
  echo " "
  echo "    certify/install"
  echo " "
fi


