#!/bin/bash

#############################
#                           
#  Base setup for Webapp Development Box  
#
#############################

echo " "
echo "In preparation for installs, update repositories..." 
sudo apt-get update

echo " "
echo "In case they're not there... install vim, git, curl, wget, openssh, ufw..."
sudo apt-get install -y vim git curl wget openssh-server ufw

echo " "
echo "Installing c, c++, java 1.8, python3 dev"
sudo apt-get install -y build-essential openjdk-8-jdk python3-dev 

echo " "
echo "Installing dev tools pip, maven"
sudo apt-get install -y python3-pip maven
sudo -H pip3 install --upgrade pip

echo " "
echo "Setting the firewall to allow ssh, http, https traffic" 
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable

echo " "
echo "Installing nginx (reverse proxy)"
sudo apt-get -y install nginx
sudo systemctl stop nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/pristine
sudo cp base/webdevbox.html /var/www/html/webdevbox.html
sudo chmod a+rw /var/www/html
sudo sed -i "s/ index.htm / index.htm webdevbox.html /g" /etc/nginx/sites-available/default
sudo systemctl enable nginx
sudo systemctl start nginx

echo " "
echo "-----------------------------------------------------"
echo " "
echo "You should be able to go to "
echo " *  http://localhost with your local browser on webdevbox, or"
echo " *  http://<hostname> from some other box on your network,"
echo "and see the nginx welcome page.  Note:  if Firefox gets testy"
echo "about using http instead of https, I apologize (for them)."
echo " "

