#!/bin/bash

# Used to blow away nginx so we can test install 
# in a semi-pristine environment.

echo " "
echo "Blowing away nginx."
sudo systemctl stop nginx 
sudo apt-get -y purge nginx nginx-common
sudo apt-get -y autoremove
sudo rm -rf /etc/nginx
sudo rm /var/www/html/webdevbox*

